export const PORTFOLIO_ITEMS = [
  {
    id: "p1",
    title: "Goggaliefies",
    href: "https://www.goggaliefies.co.za",
    img: "/images/schoolFront750.jpg",
    target: "blank",
    priority: "true",
    rel: "noreferrer",
    alt: "Goggaliefies",
    comments: "",
  },
  {
    id: "p2",
    title: "Ai-Ais Resort (NWR)",
    href: "http://www.aiaisresort.com",
    img: "/images/aiaisresort-ind.png",
    target: "_blank",
    priority: "true",
    rel: "noreferrer",
    alt: "Ai-Ais Resort (NWR)",
    comments: "",
  },
  {
    id: "p3",
    title: "Namibia Wildlife Resorts",
    href: "http://www.nwrnamibia.com",
    img: "/images/nwrnamibia.png",
    target: "_blank",
    priority: "true",
    rel: "noreferrer",
    alt: "Namibia Wildlife Resorts",
    comments: "",
  },
  {
    id: "p4",
    title: "Sossus Dune Lodge (NWR)",
    href: "http://www.sossusdunelodge.com",
    img: "/images/sossusdunelodge-ind.png",
    target: "_blank",
    priority: "true",
    rel: "noreferrer",
    alt: "Sossus dune lodge - Namibia Wildlife Resorts",
    comments: "",
  },
  {
    id: "p5",
    title: "Advanced form",
    href: "/contactPage",
    img: "/images/advanceForm.png",
    target: "_blank",
    priority: "true",
    rel: "noreferrer",
    alt: "Advanced forms",
    comments: "",
  },
  {
    id: "p6",
    title: "Radio Vision",
    href: "http://www.radiovision.co.za",
    img: "/images/radioVision.jpg",
    target: "_blank",
    priority: "true",
    rel: "noreferrer",
    alt: "Radio vision",
    comments: "",
  },
  {
    id: "p7",
    title: "Namibia bookings",
    href: "http://www.namibiabookings.com",
    img: "/images/namibiabookings.png",
    target: "_blank",
    priority: "true",
    rel: "noreferrer",
    alt: "Namibia Wildlife Resorts and alternative accommodation",
    comments: "",
  },
  {
    id: "p8",
    title: "Namibia Wild Life Resorts",
    href: "http://www.nwrnamibiawildliferesorts.com",
    img: "/images/nwrnamibiawildliferesorts.png",
    target: "_blank",
    priority: "true",
    rel: "noreferrer",
    alt: "Namibia Wildlife Resorts",
    comments: "",
  },
  {
    id: "p9",
    title: "Reserve This Spot",
    href: "/contactPage",
    img: "/images/pexels-mateusz-dach-450035.jpg",
    target: "_blank",
    priority: "true",
    rel: "noreferrer",
    alt: "Call Lesawi to reserve this spot",
    comments: "",
  },
];

export function getAllPortfolioItems() {
  return PORTFOLIO_ITEMS;
}

export function getPortfolioItemById(id) {
  return PORTFOLIO_ITEMS.find((port) => port.id === id);
}
